HDY-91-92
ramirofazio/hydrotek-backend pull request #6
Opened 2023-09-06 03:03 UTC by ramirofazio

>[!NOTE]
>- Se cambio el comando de `docker run -d --name hydrotek-db -p 5432:5432 hydrotek-db` por `docker compose up`
>   - `docker compose up` = levanta el docker compose, generando la db y generando el volumen **db-data**
>   - `--build`= con la flag **build** hace que la imagen y el contenedor se genered de nuevo

Cree controladores y servicios en `user`, `auth` y `role`, agregue un **docker-compose** para generar [`VOLUMENES`](https://docs.docker.com/storage/volumes/) y tener persistencia de la db, ademas se implemento `JWT` en el signIn y el hasheo de contraseñas con `bcrypt`.
-
#### Rutas Añadidas:
- `auth/signUp`: A través de **POST** un usuario puede registrarse, su contraseña de hashea y se le ponen datos por default en props. `role`,  `active` y `dni`. 

Ejemplo de **POST `auth/signUp`**: 

```
{
	"name": "Ramiro Fazio Dattoli",
	"email": "ramifazio2@gmail.com",
	"password": "#ABC561sssd82303!"
}
```

**Response**:

```
{
	"id": "75bed571-61d9-477f-b615-3086d6e898a7",
	"name": "Ramiro Fazio Dattoli",
	"dni": null,
	"email": "ramifazio2@gmail.com",
	"password": "$2b$10$7YuKiJAHqI63p4Kzrgw6rOMsnnYyd.Jsc54LaFHIJ1JaxJxnwmCdm",
	"active": true,
	"roleId": 1
}
```
- `auth/signIn`: A través de **POST** un usuario puede loguearse con su `email` y `contraseña` (momentaneamente) para luego obtener un **JWT**.

Ejemplo de **POST `auth/signIn`**: 

```
{
	"email": "ramifazio2@gmail.com",
	"pass": "#ABC561sssd82303!"
}
```

**Response**:

```
{
	"access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NWJlZDU3MS02MWQ5LTQ3N2YtYjYxNS0zMDg2ZDZlODk4YTciLCJuYW1lIjoiUmFtaXJvIEZhemlvIERhdHRvbGkiLCJhZG1pbiI6MSwiaWF0IjoxNjkzOTY4NTA4LCJleHAiOjE2OTM5Njg1Njh9.Sj87b3UJp4I1UjX4FAo7SJjUEJyfoGy2v6OFhJ9t-9Q"
}
```
-
#### Service Role:
- Se añadio un service Role que genera automaticamente los roles si es que no existen en la `DB` 

   > main.ts
   - `19 | await app.get(RoleService).createRolesIfNotExist();`

2023-09-06 03:08 UTC, ramirofazio commented
@TomasPerez1 No puedo hacer parar el test de `lint`. Me marca que no uso cosas que si estoy usando 😆

2023-09-07 00:07 UTC, josesantangelo requested changes
Rama, fijate que varios de los errores de eslint son por los constructors. agregales el comentario "// eslint-disable-next-line no-unused-vars" en la linea superior. En el caso del DTO, la libreria class-validator tiene todos los metodos duplicados. Ej existe un metodo isNumber, y otro IsNumber. Fijate de estar usando el mismo que importas. No lo puedo ver bien porque nose sacar el cartelito :)

2023-09-07 01:17 UTC, ramirofazio commented
> Rama, fijate que varios de los errores de eslint son por los constructors. agregales el comentario "// eslint-disable-next-line no-unused-vars" en la linea superior. En el caso del DTO, la libreria class-validator tiene todos los metodos duplicados. Ej existe un metodo isNumber, y otro IsNumber. Fijate de estar usando el mismo que importas. No lo puedo ver bien porque nose sacar el cartelito :)

Que cartelito jose? Ahi me fije y en los DTO que me tira error de eslint estoy importando y usando los mismos. medio rari

2023-09-07 03:09 UTC, ramirofazio commented
@josesantangelo Ya arregle esas cositas y agregue una validaciones. Hay un problema con el prismaClient, Aunque al campo `dni` le haya puesto opcional desde el schema, me sigue diciendo que es requerido según el modelo. Ahi lo arregle para que este o no este, pero no puedo validarlo mucho desde el **DTO**. Raroooo

2023-09-07 12:50 UTC, josesantangelo approved these changes

2023-09-07 12:50 UTC, merged

2023-09-09 20:17 UTC, ramirofazio commented
@TomasPerez1 este PR